// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMHE67xIUsuwyhzgXyB-PEmNOhI-jb4s8',
    appId: '1:777567970725:web:9589299ba19c8ee262744c',
    messagingSenderId: '777567970725',
    projectId: 'chat-app-flutter-fb',
    authDomain: 'chat-app-flutter-fb.firebaseapp.com',
    storageBucket: 'chat-app-flutter-fb.appspot.com',
    measurementId: 'G-BDE1Q7413T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiV4jmsAbnGCrV8FuWqWh2xHFBaUhQlIs',
    appId: '1:777567970725:android:91828d80a559753c62744c',
    messagingSenderId: '777567970725',
    projectId: 'chat-app-flutter-fb',
    storageBucket: 'chat-app-flutter-fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsYVrrmTNp1tdBMn2lFI4QcLAM79wHuGc',
    appId: '1:777567970725:ios:bda19d3a84d1e92c62744c',
    messagingSenderId: '777567970725',
    projectId: 'chat-app-flutter-fb',
    storageBucket: 'chat-app-flutter-fb.appspot.com',
    iosBundleId: 'com.dev.chatAppFlutter',
  );
}
